brands_map = {
    'ЯДХ': "YADAH",
    'СМ': "THE SAEM",
    'ВЛК': "WELCOS",
    'ЕОН': "THE YEON",
    'ФШ': "THE FACE SHOP",
    'SB': "SUNG BO CLEAMY",
    'СНП': "SNP",
    'СФ': "SKINFOOD",
    'СНГ': "SINGI",
    'СК': "Secret Key",
    'SS': "SECRET SKIN",
    'СТР': "SEA N TREE",
    'PP': "RIRE",
    'ПТФ': "PETITFEE",
    'НР': "NATURE REPUBLIC",
    'МКН': "MUKUNGHWA",
    'МЗ': "MIZON",
    'МЛТ': "MILATTE",
    'МЖ': "MIJIN",
    'ЛЛ': "LIOELE",
    'ЛБТ': "LABIOTTE",
    'ЛД': "LADOR",
    'КСН': "LADOR",
    'ДЖН': "JUNGNANI",
    'ХК': "HAKEN",
    'ЛБ': "GAIN COSMETIC",
    'G9': "G9SKIN",
    'ENL': "EYENLIP BEAUTY",
    'ЭХ': "ETUDE HOUSE",
    'ЕНФ': "ENOUGH",
    'ЕЛЗ': "ELIZAVECCA",
    'DGL': "DR.GLODERM",
    'ДП': "DEOPROCE",
    'КСР': "COSRX",
    'КЛИ': "CLIO",
    'СР': "CIRACLE",
    'БР': "BERRISOM",
    'БГР': "BEAUUGREEN",
    'БХ': "URBAN DOLLKISS",
    'АЮМ': "AYOUME",
    'АН': "ANSKIN",
    'АП': "A'PIEU",
    'ФС': "FASCY",
    'ЭТТ': "ETTANG",
    'БЛП': 'Bling Pop',
    'ДГМ': 'Daeng Gi Meo Ri',
    'ГРС': 'GUERISSON',
    'ИНС': 'INNISFREE',
    'МСЛ': 'MAYISLAND',
    'ПГН': 'PIGEON',
    'РБ': 'RUBELLI',
    'СБМ': 'SOMEBYMI',
    'СКХ': 'THE SKIN HOUSE',
    'TIA': 'TIAM',
    # KOREA TRADE
    "A’pieu": "A'PIEU",
    "A'PIEU": "A'PIEU",
    '3W': '3W CLINIC',
    'ENOUGH': 'ENOUGH',
    'Elizavecca': 'Elizavecca',
    'COSRX': 'COSRX',
    'ETUDE': 'ETUDE HOUSE',
    'FarmStay': 'FarmStay',
    'Innisfree': 'Innisfree',
    "IT'S": "IT'S SKIN",
    'IYOUB': 'IYOUB',
    'JIGOTT': 'JIGOTT',
    "La'dor": "Lador",
    'LANEIGE': 'LANEIGE',
    'LEBELAGE': 'LEBELAGE',
    'Mise': 'Mise en scene',
    'MISE': 'Mise en scene',
    'MIZON': 'MIZON',
    'Petitfee': 'Petitfee',
    'Secret': 'Secret Key',
    'SKINFOOD': 'SKINFOOD',
    'THE': 'THE FACE SHOP',
    'VILLAGE': 'VILLAGE 11 FACTORY',
}


brands_list = [v for k,v in brands_map.items()]